apiVersion: apps/v1
kind: Deployment
metadata:
  name: basal-manager
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basal-manager
  template:
    metadata:
      labels:
        app: basal-manager
    spec:
      containers:
        - name: basal-manager
          image: uhub.service.ucloud.cn/entropypool/basal-manager:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/BasalManager
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: basal-manager-config
            items:
              - key: service-conf
                path: BasalManager.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: basal-manager
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50620
      targetPort: 50620
    - name: grpc
      port: 50621
      targetPort: 50621
    - name: healthz
      port: 50622
      targetPort: 50622
    - name: prometheus
      port: 50623
      targetPort: 50623
  selector:
    app: basal-manager
